In [1]:
# Import the library
import torch
import torch.nn as nn

# Define the input data as a 2-D tensor
x = torch.tensor([[0.,1.],[2.,3.]])
#Shape
print('input_data:', x.shape)

# Create an instance of the nn.Linear class
output_size = 1
linear_layer = nn.Linear(in_features=2,
                         out_features=output_size,
                         bias = True,
                         dtype= torch.float)

# Apply the linear transformation to the input data
y = linear_layer(x)

#print the outputs
print('output:\n',y)

#print the outputs shape
print('output Shape:', y.shape)

input_data: torch.Size([2, 2])
output:
 tensor([[ 5.2034e-04],
        [-8.4894e-01]], grad_fn=<AddmmBackward0>)
output Shape: torch.Size([2, 1])


In [2]:
linear_layer.weight

Parameter containing:
tensor([[-0.3632, -0.0615]], requires_grad=True)

In [3]:
0*0.2342 +1*0.2202 +0.3108

0.531

In [4]:
2*0.2342 +3*0.2202 +0.3108

1.4398

In [5]:
linear_layer.bias

Parameter containing:
tensor([0.0621], requires_grad=True)

In [6]:
# Linear layer weight
A = linear_layer.weight
#Bias
b = linear_layer.bias

#Output
y = x @ A.transpose(0,1) + b

#print the outputs
print(y)

tensor([[ 5.2034e-04],
        [-8.4894e-01]], grad_fn=<AddBackward0>)


In [7]:
# Import the library
import torch
import torch.nn as nn

# Define the input data as a 3-D tensor
x = torch.tensor([[[0.,1.,2.],
                   [3.,4.,5.],
                   [6.,7.,8.]]])

print('input_data:', x.shape)

# Create an instance of the nn.Linear class
output_size = 5
linear_layer = nn.Linear(in_features=x.size()[-1],
                         out_features=output_size,
                         bias = True,
                         dtype= torch.float)

# Apply the linear transformation to the input data
y = linear_layer(x)
#print the outputs
print('\noutput:\n',y)

#print the outputs shape
print('\noutput Shape:', y.shape)

input_data: torch.Size([1, 3, 3])

output:
 tensor([[[ 0.6459,  1.6087,  0.8136,  0.6045, -0.5220],
         [ 3.8673,  3.2328,  1.0198,  2.3628, -3.5239],
         [ 7.0886,  4.8568,  1.2260,  4.1212, -6.5257]]],
       grad_fn=<AddBackward0>)

output Shape: torch.Size([1, 3, 5])


In [8]:
# Linear layer weight
A = linear_layer.weight
#Bias
b = linear_layer.bias

#Output y= xA^T + b
##Matrix product of two tensors
y = x.matmul(A.transpose(0,1)) + b

#print the outputs
print(y)

tensor([[[ 0.6459,  1.6087,  0.8136,  0.6045, -0.5220],
         [ 3.8673,  3.2328,  1.0198,  2.3628, -3.5239],
         [ 7.0886,  4.8568,  1.2260,  4.1212, -6.5257]]],
       grad_fn=<AddBackward0>)


In [9]:
# Import the library
import torch
import torch.nn as nn

# Define the input data as a 3-D tensor
batch_size = 2
num_channels = 3
input_size = 4

input_data = torch.randn(size =(batch_size, num_channels, input_size))
print('input Shape :', input_data.shape)
print('Input\n',input_data)

# Create an instance of the nn.Linear class
output_size = 2
linear_layer = nn.Linear(in_features=input_data.size()[-1],
                         out_features=output_size,
                         bias = True)

# Apply the linear transformation to the input data
output = linear_layer(input_data)
print('\noutput shape:', output.shape)
print('output:\n',output)

input Shape : torch.Size([2, 3, 4])
Input
 tensor([[[ 0.3476,  0.7919,  1.5323, -0.8997],
         [-1.8786,  1.0118, -0.7519,  1.1459],
         [ 0.6059,  0.6277,  1.8698, -0.1176]],

        [[-0.4494,  0.5984, -1.2178, -0.8907],
         [ 0.2122,  1.2884, -2.1112, -1.3553],
         [ 2.1322, -1.2430,  0.1479, -1.1327]]])

output shape: torch.Size([2, 3, 2])
output:
 tensor([[[ 0.4646,  0.5813],
         [-0.1456, -1.8252],
         [ 0.4371,  0.5621]],

        [[ 0.3207, -0.6912],
         [ 0.6694, -0.8769],
         [ 0.6614,  1.3136]]], grad_fn=<AddBackward0>)


In [10]:
# Linear layer weight
A = linear_layer.weight
#Bias
b = linear_layer.bias

#Output y= xA^T + b
##Matrix product of two tensors
y = input_data.matmul(A.transpose(0,1)) + b

#print the outputs
print(y)

tensor([[[ 0.4646,  0.5813],
         [-0.1456, -1.8252],
         [ 0.4371,  0.5621]],

        [[ 0.3207, -0.6912],
         [ 0.6694, -0.8769],
         [ 0.6614,  1.3136]]], grad_fn=<AddBackward0>)


In [11]:
print(input_data.matmul(linear_layer.weight.transpose(0,1)) + linear_layer.bias)

tensor([[[ 0.4646,  0.5813],
         [-0.1456, -1.8252],
         [ 0.4371,  0.5621]],

        [[ 0.3207, -0.6912],
         [ 0.6694, -0.8769],
         [ 0.6614,  1.3136]]], grad_fn=<AddBackward0>)


In [12]:
linear_layer.bias

Parameter containing:
tensor([ 0.2338, -0.2107], requires_grad=True)

In [13]:
linear_layer.weight

Parameter containing:
tensor([[ 0.2599,  0.1630, -0.0347, -0.0717],
        [ 0.3154, -0.3083,  0.3918, -0.3625]], requires_grad=True)

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.a1 = nn.Linear(4,4)
        self.a2 = nn.Linear(4,4)
        self.a3 = nn.Linear(9,1)
    def forward(self,x):
        o1 = self.a1(x)
        o2 = self.a2(x).transpose(1,2)
        output = torch.bmm(o1,o2)
        output = output.view(len(x),9)
        output = self.a3(output)
        return output

x = torch.tensor([[[1.,2.,3.,4.],
                  [5.,6.,7.,9.],
                  [10.,11.,12.,13.]]])

y = torch.tensor([[20.],
                  [54.],
                  [92.]
                 ])

net = Net()

criterion = nn.MSELoss()
optimizer = optim.Adam(net.parameters())

for i in range(10):
    net.zero_grad()
    output = net(x)
    loss = criterion(output,y)
    loss.backward()
    optimizer.step()
    print(loss.item())

4896.93994140625
4759.88037109375
4627.23876953125
4498.98193359375
4375.05126953125
4255.35107421875
4139.74267578125
4028.032470703125
3919.973876953125
3815.2607421875


/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py:529: UserWarning: Using a target size (torch.Size([3, 1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [15]:
net.a1.weight

Parameter containing:
tensor([[-0.4764,  0.0510,  0.2604, -0.4536],
        [-0.4556,  0.3977, -0.1882, -0.2244],
        [ 0.0373, -0.0495,  0.4324, -0.0685],
        [-0.0864, -0.2992, -0.2550, -0.4637]], requires_grad=True)

In [16]:
net.a2.weight

Parameter containing:
tensor([[-0.2849,  0.1871, -0.3150, -0.1994],
        [-0.1807, -0.2677, -0.1517, -0.3915],
        [ 0.4222, -0.4721,  0.2070,  0.1292],
        [ 0.1044,  0.4443,  0.3731, -0.1088]], requires_grad=True)

In [17]:
net.a3.weight

Parameter containing:
tensor([[ 0.1485, -0.2394, -0.0733,  0.1102,  0.2174,  0.2683,  0.0015,  0.1498,
          0.0271]], requires_grad=True)

In [18]:
net.forward

<bound method Net.forward of Net(
  (a1): Linear(in_features=4, out_features=4, bias=True)
  (a2): Linear(in_features=4, out_features=4, bias=True)
  (a3): Linear(in_features=9, out_features=1, bias=True)
)>

In [19]:
net(x)

tensor([[1.9604]], grad_fn=<AddmmBackward0>)

In [20]:
x = torch.tensor([[[1.,2.,3.,4.],
                  [5.,6.,7.,9.],
                  [10.,11.,12.,13.]]])
net.a1(x)

tensor([[[ -1.2839,  -0.9139,   0.7685,  -3.1914],
         [ -4.2122,  -3.0208,   2.1067,  -8.0720],
         [ -6.8519,  -5.1495,   3.9337, -13.1295]]], grad_fn=<AddBackward0>)

In [21]:
net.a2(x)

tensor([[[ -1.7110,  -3.1138,   0.9266,   2.1596],
         [ -4.3594,  -7.4716,   2.2015,   5.3028],
         [ -7.2212, -12.0379,   3.5043,   9.4765]]], grad_fn=<AddBackward0>)

In [22]:
net.a3(torch.bmm(net.a1(x),net.a2(x).transpose(1,2)).view(len(x),9))

tensor([[1.9604]], grad_fn=<AddmmBackward0>)

In [23]:
x.shape

torch.Size([1, 3, 4])

In [24]:
x = torch.randn(1,3,4)
x

tensor([[[-1.0413,  1.2856,  0.5482,  0.4639],
         [-0.7475,  0.3375, -0.4623,  0.9720],
         [ 1.1361, -0.0663, -1.3794, -0.2513]]])

In [25]:
k=x*5
k[:,0,:]

tensor([[-5.2067,  6.4282,  2.7409,  2.3197]])

In [26]:
k[:,0,:].sum()

tensor(6.2822)

In [27]:
k[:,1,:].sum()

tensor(0.4980)

In [28]:
k[:,2,:].sum()

tensor(-2.8041)

In [29]:
y.size()

torch.Size([3, 1])