In [1]:
import torch

In [2]:
torch.__version__

'1.13.1+cu117'

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,10)
arr.dtype

dtype('int32')

## Convert to PyTorch Tensor

In [5]:
Tensor = torch.from_numpy(arr)
Tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [6]:
# Indexing
Tensor[2:]

tensor([2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [7]:
Tensor[2:5]

tensor([2, 3, 4], dtype=torch.int32)

In [8]:
len(Tensor)

10

In [9]:
type(Tensor)

torch.Tensor

In [10]:
Tensor[5]=50

In [11]:
Tensor

tensor([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9], dtype=torch.int32)

In [12]:
arr

array([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9])

## Torch.tensor

In [13]:
arr = np.arange(0,20)
tensor = torch.tensor(arr)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19], dtype=torch.int32)

In [14]:
tensor[4]=40
tensor

tensor([ 0,  1,  2,  3, 40,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19], dtype=torch.int32)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
tensor[2:]

tensor([ 2,  3, 40,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       dtype=torch.int32)

In [17]:
tensor[2:5]

tensor([ 2,  3, 40], dtype=torch.int32)

In [18]:
tensor.type

<function Tensor.type>

In [19]:
type(tensor)

torch.Tensor

In [20]:
arr= arr.reshape(4,5)
tensor = torch.tensor(arr)
tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]], dtype=torch.int32)

In [21]:
tensor.shape

torch.Size([4, 5])

In [22]:
tensor[2]

tensor([10, 11, 12, 13, 14], dtype=torch.int32)

In [23]:
tensor[:,3]

tensor([ 3,  8, 13, 18], dtype=torch.int32)

In [24]:
tensor[2,3]

tensor(13, dtype=torch.int32)

In [25]:
tensor[2:,3:]

tensor([[13, 14],
        [18, 19]], dtype=torch.int32)

In [26]:
# Zeros and ones
torch.zeros(3,5, dtype = torch.int)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [27]:
torch.ones(3,5, dtype = torch.float64)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

## Arithemetic progression

In [28]:
a = torch.tensor([1,2,3], dtype = torch.float16)
b = torch.tensor([3,4,5], dtype = torch.float16)

In [29]:
a+b

tensor([4., 6., 8.], dtype=torch.float16)

In [30]:
torch.add(a,b)

tensor([4., 6., 8.], dtype=torch.float16)

In [31]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [32]:
torch.add(a,b, out = c)

tensor([4., 6., 8.])

In [33]:
c

tensor([4., 6., 8.])

In [34]:
# Multiplication

a.mul(b)

tensor([ 3.,  8., 15.], dtype=torch.float16)

In [35]:
a*b

tensor([ 3.,  8., 15.], dtype=torch.float16)

In [36]:
torch.multiply(a,b,out = c)

tensor([ 3.,  8., 15.])

In [37]:
c

tensor([ 3.,  8., 15.])

In [38]:
c.sum()

tensor(26.)

## Matrix multiplication 

In [39]:
a = torch.tensor([[1,2,3],[3,4,5]], dtype = torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype = torch.float)

In [40]:
a

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [41]:
b

tensor([[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [42]:
torch.matmul(a,b)

tensor([[ 52.,  58.],
        [100., 112.]])

In [43]:
torch.mm(a,b)

tensor([[ 52.,  58.],
        [100., 112.]])

In [44]:
a@b

tensor([[ 52.,  58.],
        [100., 112.]])